### ISSUE TITLE
Add a big logo at the top?

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/.github#2]
It would leave a better impression if the logo was bigger, and above everything else, imo.

 s <- BIG logo of sern
------
/ hey this is us, Sern handler

**Comment by Murtatrxx** [comment]
I don’t know, it already looks nice I think
btw I was thinking about rounded logo.

**Comment by jacoobes** [comment]
Alright. I'll trust you on that
Let's see how it looks rounded. I also want to test transparent.

**Comment by Murtatrxx** [comment]
👍👌
